version: '3.4'

services:
  reactpokemonsapp:
    image: reactpokemonsapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      REACT_APP_ENVIRONMENT: production
    ports:
      - 3000:3000
    networks:
      - docker-service

networks:
  docker-service:
    driver: bridge